apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: azure-blob-tls
  namespace: envoy-poc
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: azure-blob-storage
  validation:
    wellKnownCACertificates: System
    hostname: tmpenvoypoc.blob.core.windows.net
