apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: reverse-proxy-route
  namespace: envoy-poc
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: reverse-proxy-gateway
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: azure-blob-storage
      matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            hostname: tmpenvoypoc.blob.core.windows.net
