apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - envoy-proxy-config.yaml
  - gateway.yaml
  - httproute.yaml
  - backend-tls-policy.yaml
  - backend.yaml
  - cnpg/azure-store.yaml

patches:
  - target:
      kind: Secret
      name: azure-storage-creds
    path: cnpg/azure-secret.yaml
