apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-test
spec:
  cluster:
    name: pg-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-test-proxy
spec:
  cluster:
    name: pg-cluster-proxy
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io