apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-test-proxy
  namespace: envoy-poc
spec:
  cluster:
    name: pg-cluster-proxy
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io